name:                happy-chem
version:             0.1.0.0
github:              "githubuser/happy-chem"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/happy-chem#readme>

dependencies:
- base >= 4.7 && < 5
- http-types >= 0.9.1
- wai >= 3.2
- warp >= 3.2.23

library:
  source-dirs: src

executables:
  happy-chem-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - happy-chem

tests:
  happy-chem-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - happy-chem
